# Generated by Django 4.2.5 on 2024-01-13 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.CharField(max_length=1000000)),
                ('Created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
